
services:
  # App-Service für die Symfony-Anwendung
  app:
    build: ./.docker/app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8082}:80"
    volumes:
      - .:/var/www/symfony
    networks:
      - docs-kaderblick-net

networks:
  docs-kaderblick-net:
    driver: bridge
