import { chromium } from '/media/Austausch/Projekte/fussballverein/Kaderblick-Website/frontend/node_modules/playwright/index.mjs';
import { mkdir, writeFile } from 'node:fs/promises';
import { waitForReady } from './lib/wait-for-ready.mjs';
const output=new URL('../var/games-audit/',import.meta.url);await mkdir(output,{recursive:true});const browser=await chromium.launch({headless:true,executablePath:'/usr/bin/google-chrome'});const context=await browser.newContext({viewport:{width:1440,height:1200},locale:'de-DE',storageState:new URL('../var/ui-audit/player/storage-state.json',import.meta.url).pathname});const page=await context.newPage();const failures=[];page.on('response',r=>{if(r.url().includes('/api/')&&r.status()>=400)failures.push(`${r.status()} ${r.url()}`)});
async function clean(){const p=page.getByText(/Wir respektieren deine Privatsphäre/i).first();if(await p.isVisible().catch(()=>false))await p.evaluate(node=>{let e=node;while(e&&e!==document.body){if(getComputedStyle(e).position==='fixed'){e.remove();return}e=e.parentElement}})}
await page.goto('https://demo.kaderblick.de/games',{waitUntil:'networkidle',timeout:30000});await clean();let main=page.locator('main').first();await waitForReady(page,main);const season=page.getByRole('combobox',{name:/Saison/i}).first();if(await season.isVisible().catch(()=>false)){await season.click();const old=page.getByRole('option',{name:'2024/25'});if(await old.isVisible().catch(()=>false)){await old.click();await waitForReady(page,main);}}await main.screenshot({path:new URL('overview.png',output).pathname});await writeFile(new URL('uebersicht.txt',output),await main.innerText());
const cards=main.locator('.MuiCardActionArea-root');let opened=false;if(await cards.count()>1){await cards.nth(1).click();opened=true;}else if(await cards.count()){await cards.first().click();opened=true;}
if(opened){await page.waitForURL(/\/games\/\d+/,{timeout:15000});main=page.locator('main').first();await waitForReady(page,main);await main.screenshot({path:new URL('detail.png',output).pathname});await page.screenshot({path:new URL('detail-gesamt.png',output).pathname,fullPage:true});await writeFile(new URL('detail.txt',output),await main.innerText());await writeFile(new URL('detail-url.txt',output),page.url());const add=page.getByRole('button',{name:/Ereignis hinzufügen/i}).first();if(await add.isVisible().catch(()=>false)){await add.click();const dialog=page.getByRole('dialog').last();await waitForReady(page,dialog);await dialog.screenshot({path:new URL('ereignis-anlegen.png',output).pathname});await writeFile(new URL('ereignis-anlegen.txt',output),await dialog.innerText());}}
await writeFile(new URL('fehler.txt',output),failures.join('\n'));await browser.close();console.log('Spiele als Spieler geprüft.');
