name: Deploy to Alfahosting

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  deployment:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      # ------------------------------
      # Checkout repository
      # ------------------------------
      - uses: actions/checkout@v3

      # ------------------------------
      # Cache Composer vendors
      # ------------------------------
      - name: Cache Composer vendors
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('composer.lock') }}

      # ------------------------------
      # Generate release directory
      # ------------------------------
      - name: Generate release directory name
        id: release
        run: echo "dir=${{ secrets.MAIN_PROJECT_PATH }}/releases/$(date +%Y%m%d_%H%M%S)" >> $GITHUB_OUTPUT

      # ------------------------------
      # Prepare build files
      # ------------------------------
      - name: Prepare files
        run: |
          mkdir -p build
          cp -r docker-compose.yaml .docker .env.dist composer.json composer.lock symfony.lock assets bin config migrations public src templates translations build/

      # ------------------------------
      # Create release directory for SCP
      # ------------------------------
                
      - name: Create release directory on server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.ROOT_USER }}
          password: ${{ secrets.ROOT_PASSWORD }}
          script: |
            set -e
            mkdir -p "${{ steps.release.outputs.dir }}"
            chmod 755 "${{ steps.release.outputs.dir }}"
            chown -R ${{ secrets.PLESK_USERNAME }}:psacln "${{ steps.release.outputs.dir }}"

      # ------------------------------
      # Copy build files to server
      # ------------------------------
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.PLESK_USERNAME }}
          password: ${{ secrets.PLESK_PASSWORD }}
          source: "build/*"
          target: "${{ steps.release.outputs.dir }}"
          strip_components: 1

      # ------------------------------
      # Prepare .env files
      # ------------------------------
      - name: Prepare .env files
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.ROOT_USER }}
          password: ${{ secrets.ROOT_PASSWORD }}
          script: |
            set -e
            RELEASE_DIR="${{ steps.release.outputs.dir }}"
            cd "$RELEASE_DIR"

            cp .env.dist .env
            sed -i 's/^APP_ENV=dev$/APP_ENV=prod/' .env

      # ------------------------------
      # Build & start
      # ------------------------------
      - name: Build
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.ROOT_USER }}
          password: ${{ secrets.ROOT_PASSWORD }}
          script: |
            set -e
            RELEASE_DIR="${{ steps.release.outputs.dir }}"
            cd "$RELEASE_DIR"
            
            chmod -R 755 "$RELEASE_DIR"
            chown -R kaderblick-ftp-admin:psacln "$RELEASE_DIR"

            docker compose --remove-orphans app
            docker compose up -d --build --force-recreate app

      # ------------------------------
      # Composer
      # ------------------------------
      - name: Composer
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PLESK_HOST }}
          username: ${{ secrets.ROOT_USER }}
          password: ${{ secrets.ROOT_PASSWORD }}
          script: |
            set -e
            RELEASE_DIR="${{ steps.release.outputs.dir }}"
            cd "$RELEASE_DIR"

            docker compose exec -T app composer install --no-dev --optimize-autoloader
